services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
